### ISSUE TITLE
Bedtools "Intersect multiple sorted BED files" tool form graphic link is dead

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#406]
Minor. Remove or replace

<img width="739" alt="screen shot 2015-11-19 at 8 11 33 am" src="https://cloud.githubusercontent.com/assets/8999735/11276045/4d67d1e6-8e95-11e5-846e-cefba4aceb22.png">
.

**Comment by yhoogstrate** [comment]
@jennaj Which tool is this exactly? "Intersect intervals" or "multiple intersect"?  When I grep for "mbi.png" it gives no results.

**Comment by jennaj** [comment]
Part of the bedtools suite. The tool display name is in the title. 

Multiple intersect is my best guess from the tool history:
<img width="570" alt="screen shot 2016-02-08 at 9 19 41 am" src="https://cloud.githubusercontent.com/assets/8999735/12893332/55a33a18-ce45-11e5-9bce-7827346efd6f.png">

This is the repo:
https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/607c0576c6ab

The bedtools tool group on http://usegalaxy.org has multiple versions these tools and all link to the repo above. If this is one of the deprecated/replaced tools now (likely), then we don't need to update the problem link. Those no longer active probably just need to be hidden. 

@natefoo Do I have this right? Should this be closed out and new ticket created in the /galaxy repo for the "hide deprecated bedtools on main" request?

**Comment by natefoo** [comment]
It looks like these were fixed, we probably just need to update the tools?

https://github.com/galaxyproject/tools-iuc/commit/c6e4cbf6727517f198d0f47fc74bc06341cad2de#diff-253abc6f4211dae7679f9b77d2247537L110

**Comment by jennaj** [comment]
Thanks @natefoo - I think that is the "new" version of the tool and it is already on main. It is the old one (a dup) with a problem that is still shown in the tool panel. (The whole tools suite is duplicated).

Tool name **Intersect multiple sorted BED files**

The first one listed in the tool panel is the updated version, corrected and linked to the diff above:
Intersect multiple sorted BED files (Galaxy Version 2.22.0)

The second is the older version, the one I think we should hide:
Intersect multiple sorted BED files (Galaxy Version 0.1.0)

Links are minor fixes, but that is done. But we can use this ticket now to track removing the duplicates/deprecated bedtools from the tool panel. Or make a new one under /galaxy and link it in.

**Comment by natefoo** [comment]
@martenson Can you fix up the tools on Main please?

**Comment by martenson** [comment]
@nate @jennaj I have hidden the old aaronquinlain's bedtools on Main

**Comment by jennaj** [comment]
Looks great, thanks!
