### ISSUE TITLE
cutadapt does not error out on wrong inputs

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#5655]
I see those here: 

ERROR: Error in sequence file at unknown line: Reads are improperly paired. Read name 'M02975:128:000000000-L7942:1:1101:16565:2314 1:N:0:74' in file 1 does not match 'M02975:128:000000000-L7942:1:1101:17520:2235 2:N:0:73' in file 2.

In a file report.txt in the working dir. The tool does not error out and runs for days without result.

@TomHarrop is this something for you and your team?

**Comment by bernt-matthias** [comment]
Sounds like something to report upstream.

**Comment by TomHarrop** [comment]
Cutadapt is supposed to check the reads, https://cutadapt.readthedocs.io/en/stable/reference.html#properly-paired-reads:

>When reading paired-end reads, Cutadapt compares the read IDs of R1 and R2 and prints an error message and aborts if they do not match.

We could add a test to the wrapper and report if it's not happening?

**Comment by bernt-matthias** [comment]
Apparently, this does not happen. So it's an upstream bug. 

> We could add a test to the wrapper and report if it's not happening?

With a test we could check the error condition, but the program would still continue to run .. needlessly.

**Comment by TomHarrop** [comment]
Hi @bgruening 

I couldn't reproduce this with a toy dataset. Cutadapt detects the mismatched reads and exits with exit code 1. There's a test in this PR: https://github.com/galaxyproject/tools-iuc/pull/5696

Do you want to share the dataset with me?

**Comment by mvdbeek** [comment]
@bgruening First thing to check here is if the exit code is actually set to 0, or if this is a problem with e.g. not collecting work dir outputs in pulsar.

**Comment by bgruening** [comment]
I will keep an eye on it. It could very well be an embedded pulsar bug. But I think cutadapt was still running ... I need to debug it.

Thanks for the test @TomHarrop that is very helpful!

**Comment by bernt-matthias** [comment]
Fixed in https://github.com/galaxyproject/tools-iuc/pull/5696

**Comment by bgruening** [comment]
I still see that. Maybe related https://github.com/marcelm/cutadapt/issues/525

**Comment by bgruening** [comment]
This is the latest error message:

```
This is   Command line parameters: -j=5 -a file:/data/dnb10/galaxy_db/files/6/1/6/dataset_6162659f-287e-4eb3-8ce8-33345b5f8d85.dat --info-file=/data/jwd02f/main/079/055/79055753/outputs/dataset_3f4b5741-0bc3-4037-9d5a-fb04fee78f25.dat -A file:/data/dnb10/galaxy_db/files/6/1/6/dataset_6162659f-287e-4eb3-8ce8-33345b5f8d85.dat --output=out1.fq.gz --paired-output=out2.fq.gz --error-rate=0.1 --times=1 --overlap=3 --action=trim --minimum-length=50 --pair-filter=any Moritz-17_S19_L001_R1_001_fastq_gz.fq.gz Moritz-92_S94_L001_R2_001_fastq_gz.fq.gz   Processing reads on 5 cores in paired-end mode ...   ERROR: Traceback (most recent call last):     File "/usr/local/tools/_conda/envs/__cutadapt@3.4/lib/python3.9/site-packages/cutadapt/pipeline.py", line 631, in run       (n, bp1, bp2) = self._pipeline.process_reads()     File "/usr/local/tools/_conda/envs/__cutadapt@3.4/lib/python3.9/site-packages/cutadapt/pipeline.py", line 428, in process_reads       for read1, read2 in self._reader:     File "/usr/local/tools/_conda/envs/__cutadapt@3.4/lib/python3.9/site-packages/dnaio/__init__.py", line 285, in __iter__       raise FileFormatError(   dnaio.exceptions.FileFormatError: Error in sequence file at unknown line: Reads are improperly paired. Read name 'M02975:91:000000000-KK9FG:1:1101:16837:1990 1:N:0:19' in file 1 does not match 'M02975:91:000000000-KK9FG:1:1101:17970:2110 2:N:0:94' in file 2.

**Comment by bernt-matthias** [comment]
Good point @wm75 :)

Maybe we should ask the UI/UX WG for displaying/highlighting to (tool/workflow) users if they are not using the latest version.

**Comment by bgruening** [comment]
To bad the JWD is gone. I was sure that I have seen a 4.3 in the config and not a 3.4. But then it was during a workshop and a bit hectic so 🤷 .... given that this is really screwing the cluster we should prevent running those old versions.
