### ISSUE TITLE
Tool shed repository 'package_perl_5_18' tool dependencies - perl error

### ISSUE THREAD

**Issue by gad83** [galaxyproject/tools-iuc#609]
Hello,

I'm on galaxy release_15.10
I tried to install the tool shed repository 'package_perl_5_18'.
It comes with two tools dependencies 
1. gnu_coreutils    8.22        package
2. perl         5.18.1  package

However, I have a error. Please take a look at the picture.
![galaxy_perl_error](https://cloud.githubusercontent.com/assets/16885762/13263075/1474152e-da36-11e5-88f6-5d0896c9c9c1.jpg)

Thank you!

**Comment by erasche** [comment]
Hi @gad83 I believe this was recently patched in Galaxy. 

- https://github.com/galaxyproject/galaxy/pull/1778
- https://github.com/galaxyproject/galaxy/pull/1775

**Comment by gad83** [comment]
Hello @erasche ,

thank you for the response.
was the fix propagated to release_15.10?

salutations,
edgar

**Comment by erasche** [comment]
I don't believe it is. @nsoranzo should we backport to 15.10?

**Comment by nsoranzo** [comment]
@erasche I'd be ok with backporting, but would it also make sense to revert the whitespace changes in #213?

**Comment by blankenberg** [comment]
There is a very good argument for reverting the whitespace changes.

**Comment by erasche** [comment]
@nsoranzo ok, go for it. I'm of the mind that it's only devs reading this so it should be legible to us, but since this will cause issues for people who aren't up-to-date, let's fix it.

**Comment by gad83** [comment]
hello guys,
any updates on this issue?

**Comment by mvdbeek** [comment]
You should be able to just update it. That specific error should be fixed with #617 and #616

**Comment by gad83** [comment]
I've "git pull" the updates.
I've restarted my instance of galaxy.
However, I still get the exact same.
Please see below the update messages to make sure I'm in the write repo:


------------
# git pull
------------
remote: Counting objects: 230, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 230 (delta 176), reused 170 (delta 170), pack-reused 33
Receiving objects: 100% (230/230), 84.29 KiB, done.
Resolving deltas: 100% (177/177), completed with 112 local objects.
From https://github.com/galaxyproject/galaxy
   6824214..36d85e8  dev        -> origin/dev
   b5949bc..d225aeb  release_15.10 -> origin/release_15.10
   8905baf..0c34d5b  release_16.01 -> origin/release_16.01
Updating b5949bc..d225aeb
Fast-forward
 .../galaxy/scripts/mvc/citation/citation-model.js  |   33 +++++++++++++------
 static/maps/mvc/citation/citation-model.js.map     |    2 +-
 static/scripts/mvc/citation/citation-model.js      |    2 +-
 3 files changed, 24 insertions(+), 13 deletions(-)

------------------
git branch -av
------------------
* release_15.10           d225aeb Merge pull request #1884 from carlfeberhard/release_15.10

**Comment by mvdbeek** [comment]
Sorry, that may not have been clear. You have to update the package in your galaxy instance,
in the admin settings -> manage tools -> get updates and then install updates

**Comment by gregvonkuster** [comment]
I'm still seeing installation problems with the latest version of package_perl_5_18 - revision 35f117d7396b.  I'm trying to install on Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux and I get this exception:

make  && make install
STDERR
CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
	  CCCMD =  cc -DPERL_CORE -c -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -std=c89 -O2  -Wall -ansi -W -Wextra -Wdeclaration-after-statement -Wendif-labels -Wc++-compat -Wwrite-strings
make[1]: *** [Makefile] Error 1
make[1]: *** [Makefile] Error 1
Unsuccessful make(cpan/Archive-Extract): code=512 at make_ext.pl line 490.
make: *** [cpan/Archive-Extract/pm_to_blib] Error 25

**Comment by mvdbeek** [comment]
Difficult to say what's the problem here ... I don't really see an error that we could go look for :/
Any ideas @bgruening @erasche ?

**Comment by mvdbeek** [comment]
It might be this weird obsession for PERL to try to write to the $HOME directory.
@gregvonkuster If you grep In your galaxy logs, do you have any permission denied errors around the time you were installing perl?

Perhaps ` if [ -d "$TMP_WORK_DIR" ] ; then export HOME=$TMP_WORK_DIR ; else export HOME=`mktemp -d` ; fi ;` and a manual configure && make && make install instead of https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_perl_5_18/tool_dependencies.xml#L11 would do the trick?!

**Comment by gregvonkuster** [comment]
Hmm...not sure, but my problem may be due to the perl installation not accounting for the requirement to have gnu_coreutils installed before perl.  In my case, perl finished before gnu_coreutils did.  I'll see if I can reproduce this.

Here's the perl recipe requirement:
```
<package name="gnu_coreutils" version="8.25">
    <repository changeset_revision="a177f177d42f" name="package_gnu_coreutils_8_25" owner="iuc" prior_installation_required="True" toolshed="https://toolshed.g2.bx.psu.edu" />
</package>
```

**Comment by mvdbeek** [comment]
bug over bug ... :/
I noticed this too, but I'm pretty sure coreutils was not the problem. If I remember well, we included coreutils to have a consistent mktmp behaviour between linux and OS X. If you're on linux, it should work without coreutils.

**Comment by mvdbeek** [comment]
http://www.perlmonks.org/?node_id=992572 gave me the idea for a potential permission problem.

**Comment by gad83** [comment]
I have something to add: there is two perl versions
![two_perls](https://cloud.githubusercontent.com/assets/16885762/13608375/8dcc769a-e522-11e5-908e-27939bd0dee7.jpg)

**Comment by gad83** [comment]
Also I get an error when I try to install gnu_coreutils:
![two_perls_error](https://cloud.githubusercontent.com/assets/16885762/13608442/cafe3c88-e522-11e5-98e2-7298c8b97215.jpg)

**Comment by mvdbeek** [comment]
@gad83 that's a bug that had been fixed in the 16.01 release (plus an additional fix that still needs to be backported from dev).
 But the good news is that perl has installed fine for you.

**Comment by gad83** [comment]
should I ignore the two other dependencies 
gnu_coreutils v8.25 
and 
perl v8.25 ????

**Comment by mvdbeek** [comment]
Yes, that should be okay. When you update galaxy to 16.01, a repair will remove the outdated dependency from the database. 

What you can do to make sure that the dependency works is to click on package_perl_5_18, then on perl under the installed tool dependencies. It will show you a path. When you go to that directory, you should find a env.sh file. If source the file [`source env.sh`], and you type `which perl`, it should give you the path to perl that galaxy will use, instead of /usr/bin/perl.

**Comment by gad83** [comment]
done and works !
thanks !!!!!!!!!!!!!!!!
