### ISSUE TITLE
Bug: PanTA requires element identifiers ending in "gff". Conflicts with new default "Auto Build List" defaults (strips extensions)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#7349]
https://github.com/galaxyproject/tools-iuc/blob/c72f529206c3362a2e7ce97922ff3cefd88a8dab/tools/panta/panta.xml#L26-L27

This is probably to satisfy Roary requirements, but the standalone Roary tool was modified to handle the use case of element identifiers without the extra ".gff" or dataset names that may include spaces. Could we change this tool to do the same thing?

XRef: https://github.com/galaxyproject/tools-iuc/pull/2546

In short, remove spaces and add in a ".gff" to whatever the original sample name is (dataset file or collection element).

Reported at https://help.galaxyproject.org/t/panaroo-panta-sample-recognition-troubleshooting/16367/2

Testing history showing both use cases with tool test 1 data -> https://usegalaxy.eu/u/jenj/h/test-panta

> **Workaround for end-users**
> 1. Name your collection's element identifers like this: `sample.gff`
>    * all one term
>    * no spaces
>    * ending with a `.gff` 
> 2. Not sure how to check your element identifiers or modify them? See this topic at the forum https://help.galaxyproject.org/t/panaroo-error-missing-dependancies/16207/6 and search our tutorials with the keyword "collection" for more!

**Comment by bernt-matthias** [comment]
Fixed in https://github.com/galaxyproject/tools-iuc/pull/7357 . Thanks @SaimMomin12

**Comment by jennaj** [comment]
Hi all -- the panaroo tools still appears to have this problem. I thought it had a seperate ticket but I can't find it.  Does anyone know? Should I open another ticket? [User Q yesterday](https://help.galaxyproject.org/t/panaroo-1-8-0-galaxy0-fails-on-gff3-collection-with-filenotfounderror-input-directory-gff/18269/2?u=jennaj) thanks!
