### ISSUE TITLE
package_trinity_2_1_1 fails with /usr/bin/ld: cannot find -lblas

### ISSUE THREAD

**Issue by ericenns** [galaxyproject/tools-iuc#780]
We tried adding LD_LIBRARY_PATH variable to lapack dependency but the issue still persists, any ideas.

**Comment by ericenns** [comment]
Full error message here:

    * installing *source* package ‘RcppArmadillo’ ...
    ** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
    ** libs
    /usr/bin/ld: cannot find -lblas
    collect2: ld returned 1 exit status
    make: *** [RcppArmadillo.so] Error 1
    ERROR: compilation failed for package ‘RcppArmadillo’
    * removing ‘/galaxy/production/tool_dependencies/trinity/2.1.1/iuc/package_trinity_2_1_1/f75117647d9c/RcppArmadillo’

**Comment by nsoranzo** [comment]
@abretaud Any idea?

**Comment by abretaud** [comment]
Thanks for reporting! As lapack is often installed by default on our servers I hadn't seen the problem

**Comment by ericenns** [comment]
This problem still occurs, as package_trinity_2_1_1, hasn't been updated to point to the latest lapack package.

**Comment by abretaud** [comment]
Oh yes, MTS is up-to-date now

**Comment by ericenns** [comment]
trinity also needs to be updated so that it uses the latest package_trinity_2_1_1 package, thanks.

**Comment by abretaud** [comment]
Done!

**Comment by ericenns** [comment]
So it turns out LD_LIBRARY_PATH didn't fix the issue instead I added LIBRARY_PATH to lapacks env.sh and then I was able to install Rcpparmadillo. I am still having issues installing package trinity, but I am not done debugging on my end yet.

**Comment by abretaud** [comment]
Thanks, it is fixed in #787!
Don't hesitate to report other problems, I can help you (though if you have a recent galaxy version, activating the conda dependencies can make things much simpler to install trinity)
